config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts
    resources :comments
  get 'pages/home'
  get 'pages/about'
  get 'pages/contact'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  has_rich_text :body
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence:true, length:{minimum:5, maximum:15}
  validates :body, presence:true, length:{minimum:10, maximum:1500}
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
     has_many :posts, dependent: :destroy
     has_many :comments, dependent: :destroy
end

app/controllers/_turbo_devise_controller.rb
 class TurboDeviseController < ApplicationController
class Responder < ActionController::Responder
    def to_turbo_stream
            controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => e
      if get?
                raise e
      elsif has_errors? && default_action
        render rendering_option.merge(format: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
      end
    end
    self.responder = Responder
    respond_to :html, :turbo_stream
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
    @comment = @post.comments.create(comment_params)
    @comment.user = current_user

    if @comment.save
      flash[:notice] = 'Comment has been created'
      redirect_to post_path(@post)
    else
      flash[:alert] = 'Comment has not been created'
      redirect_to post_path(@post)
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
before_action :authenticate_user!, except: %i[show index]
  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post.update(views: @post.views + 1)
    @comments = @post.comments.order(created_at: :desc)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/comments/_comment.html.erb
<div class = "comment-<%= comment.id %> container" style ="border: 1px solid black; padding: 1em; margin:1em;">
<%= comment.user.email %><br />
<span> Posted <%= time-ago_in_words(comment.created_at) %></span>
<% if current_user == comment.user %>
<div class="button-group float-end">
<%= button_to "Delete", [post, comment],class:"btn btn-danger", method: :delete %>
</div>
<% end %>
<hr />
<%= comment.body %>
</div>

app/views/comments/_form.html.erb
<%= form_with(model:[post, post.comments.build]) do |f| %>
<div class="form-control">
<%= f.rich_text_area :body %>
<%= f.submit "Reply",class: "btn-btn-primary-mt-1" %>
</div>
<% end %>

app/views/layouts/_alerts.html.erb
<% if notice || alert  %>
<p class = "notice"><%= notice %></p>
<p class = "alert"><%= alert %></p>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "Rails Blog",root_path,class:'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
         <%= link_to "Home",root_path,class:'nav-link active' %>
          <a  href="#"></a>
        </li>
        <li class="nav-item">
           <%= link_to "Blogs",posts_path,class:'nav-link' %>
        </li>
        <li class="nav-item">
           <%= link_to "About Us",pages_about_path,class:'nav-link' %>
        </li>
        <li class="nav-item">
           <%= link_to "contact Us",pages_contact_path,class:'nav-link' %>
        </li>
      <%= render 'users/session_manager' %>
    </div>
  </div>
</nav>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <head>
    <title>PracticeProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    
  </head>

  <body>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

  <header>
  <%= render 'layouts/navbar' %>
  <%= render 'layouts/alerts'%>
  </header>
  <main>
    <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>
</div>

app/views/pages/contact.html.erb
<div class="container">
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>
</div>

app/views/pages/home.html.erb
<div class= 'container'>
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<%= link_to "contact us", pages_contact_path %>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div class="container">
<div id="<%= dom_id post %>">
  <p>
    <strong>Title:</strong>
    <%= post.title %>
  </p>
  <h6><%= pluralize(post.views,"view") %></h6>

  <p>
    <strong>Body:</strong>
    <%= post.body %>
  </p>

</div>
</div>

app/views/posts/edit.html.erb
<div class="container">
<h1>Editing post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Show this post", @post %> |
  <%= link_to "Back to posts", posts_path %>
</div>
</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="container">
<h1>Posts</h1>

<div id="posts">
  <% @posts.each do |post| %>
    <%= render post %>
    <p>
      <%= link_to "Show this post", post %>
    </p>
  <% end %>
</div>

<%= link_to "New post", new_post_path %>
</div>

app/views/posts/new.html.erb
<div class="container">
<h1>New post</h1>

<%= render "form", post: @post %>

<br>

<div>
  <%= link_to "Back to posts", posts_path %>
</div>
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @post %>

<div>
  <%= link_to "Edit this post", edit_post_path(@post) %> |
  <%= link_to "Back to posts", posts_path %>

  <%= button_to "Destroy this post", @post, method: :delete %>
</div>

<div class="container">
<%= render 'comments/form', post:@post %>
<% @comments.each do |comment| %>
<%= render 'comments/comment',post:@post %>
<% end %>
</div>

app/views/users/_session_manager.html.erb
 <% if user_signed_in? %>
 Logged in as <strong><%= current_user.email %></strong>
   <%= link_to "Edit Profile  ", edit_user_registration_path, class:'navbar-link' %>
<%= button_to "log_out  ", destroy_user_session_path, method: :delete, class: "navbar-link" %>
 <%else%>
 <%= link_to "sign_up  ", new_user_registration_path, class:"mx-3 mt-2 me-2 " %>
 <%= link_to "login", new_user_session_path, class:'navbar-link mx-3 mt-2 me-2' %>
<% end %> 
 